### ISSUE TITLE
Serialization of Claims

### ISSUE THREAD

**Issue by jlegan** [imperugo/IdentityServer3.Contrib.Cache.Redis#1]
I do not see any custom serializers or sub classing occuring, so how did you get the Claims object to serialize?

```
  "Message": "Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type System.Security.Claims.Claim. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path '[0].Issuer', line 1, position 11.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at StackExchange.Redis.Extensions.Newtonsoft.JsonSerializer.Deserialize[T](Byte[] serializedObject)
   at StackExchange.Redis.Extensions.Newtonsoft.JsonSerializer.<>c__DisplayClassb`1.<DeserializeAsync>b__a()
```

**Comment by jlegan** [comment]
Here is how I solved it in case it helps anyone else:

```
public async Task<IEnumerable<Claim>> GetAsync(string key)
        {
            var result = await _cacheClient.GetAsync<object>(key);

            if (result != null)
            {
                return await Task.FromResult(result as IEnumerable<Claim>);
            }

            return await Task.FromResult<IEnumerable<Claim>>(null);
        }
```

**Comment by imperugo** [comment]
Hi @jlegan 
I think the problem was relater to the method GetAsync of [_cacheClient](https://github.com/imperugo/StackExchange.Redis.Extensions) (the package was old).

Just updated (also [Thinktecture.IdentityServer3](https://github.com/IdentityServer/Thinktecture.IdentityServer3)). Let me test, if it works I'll send an update today.
Thx

**Comment by imperugo** [comment]
Fixed and released on NuGet.

Thx
